// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0by3QN9NSvcxyxg4hEEZhLBpOSPJ2G4',
    appId: '1:172840829163:android:d00c60504ef85c8313feae',
    messagingSenderId: '172840829163',
    projectId: 'springhealth-d00aa',
    storageBucket: 'springhealth-d00aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4qZeMR0d78FTsVWSpby6fWGIR-amEso',
    appId: '1:527678863150:ios:2286e1c9f1ad7332eaecbf',
    messagingSenderId: '527678863150',
    projectId: 'spring-health-studio-f4930',
    storageBucket: 'spring-health-studio-f4930.firebasestorage.app',
    iosBundleId: 'com.springhealthtech.springHealthMember',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNuVVBgoJZJ7dvoljDfz0J-3wAFajDU5E',
    appId: '1:172840829163:web:50e0a382dcfe707313feae',
    messagingSenderId: '172840829163',
    projectId: 'springhealth-d00aa',
    authDomain: 'springhealth-d00aa.firebaseapp.com',
    storageBucket: 'springhealth-d00aa.firebasestorage.app',
    measurementId: 'G-4EPV8DFS9Y',
  );

}