// Mocks generated by Mockito 5.4.6 from annotations
// in spring_health_member/test/screens/social/member_wall_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spring_health_member/models/comment_model.dart' as _i7;
import 'package:spring_health_member/models/post_model.dart' as _i4;
import 'package:spring_health_member/services/social_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i2.SocialService {
  @override
  _i3.Future<void> createPost(_i4.PostModel? post, {_i5.File? imageFile}) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [post], {#imageFile: imageFile}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.PostModel>> streamFeedByBranch(
    String? branch, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamFeedByBranch, [branch], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.PostModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.PostModel>>.empty(),
          )
          as _i3.Stream<List<_i4.PostModel>>);

  @override
  _i3.Stream<List<_i4.PostModel>> streamGlobalFeed({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#streamGlobalFeed, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.PostModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.PostModel>>.empty(),
          )
          as _i3.Stream<List<_i4.PostModel>>);

  @override
  _i3.Stream<List<_i4.PostModel>> streamMemberPosts(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#streamMemberPosts, [memberId]),
            returnValue: _i3.Stream<List<_i4.PostModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.PostModel>>.empty(),
          )
          as _i3.Stream<List<_i4.PostModel>>);

  @override
  _i3.Stream<_i6.DocumentSnapshot<Object?>> getPostStream(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostStream, [postId]),
            returnValue: _i3.Stream<_i6.DocumentSnapshot<Object?>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i6.DocumentSnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i6.DocumentSnapshot<Object?>>);

  @override
  _i3.Stream<_i6.QuerySnapshot<Object?>> getCommentsStream(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsStream, [postId]),
            returnValue: _i3.Stream<_i6.QuerySnapshot<Object?>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i6.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i6.QuerySnapshot<Object?>>);

  @override
  _i3.Stream<List<_i7.CommentModel>> streamComments(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#streamComments, [postId]),
            returnValue: _i3.Stream<List<_i7.CommentModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i7.CommentModel>>.empty(),
          )
          as _i3.Stream<List<_i7.CommentModel>>);

  @override
  _i3.Future<void> addComment(String? postId, _i7.CommentModel? comment) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [postId, comment]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteComment(String? postId, String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [postId, commentId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleLike(String? postId, String? memberAuthUid) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [postId, memberAuthUid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isLikedBy(String? postId, String? memberAuthUid) =>
      (super.noSuchMethod(
            Invocation.method(#isLikedBy, [postId, memberAuthUid]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> toggleLikeWithMemberId(String? postId, String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLikeWithMemberId, [postId, memberId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
