import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:spring_health_member/core/theme/app_colors.dart';
import 'package:spring_health_member/core/theme/app_text_styles.dart';
import 'package:spring_health_member/models/post_model.dart';
import 'package:spring_health_member/services/social_service.dart';

class CreatePostScreen extends StatefulWidget {
  final String memberId;
  final String memberAuthUid;
  final String memberName;
  final String branch;
  final SocialService? socialServiceOverride;

  const CreatePostScreen({
    super.key,
    required this.memberId,
    required this.memberAuthUid,
    required this.memberName,
    required this.branch,
    @visibleForTesting this.socialServiceOverride,
  });

  @override
  State<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends State<CreatePostScreen> {
  final _textController = TextEditingController();
  final _picker = ImagePicker();
  File? _selectedImage;
  bool _isSubmitting = false;

  SocialService get _socialService => widget.socialServiceOverride ?? SocialService.instance;

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    try {
      final XFile? picked = await _picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 80,
      );
      if (picked != null) {
        setState(() {
          _selectedImage = File(picked.path);
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to pick image')),
        );
      }
    }
  }

  void _removeImage() {
    setState(() {
      _selectedImage = null;
    });
  }

  Future<void> _submitPost() async {
    final text = _textController.text.trim();
    if (text.isEmpty && _selectedImage == null) return;

    setState(() {
      _isSubmitting = true;
    });

    // Show modal loading overlay
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(
        child: CircularProgressIndicator(color: AppColors.neonLime),
      ),
    );

    try {
      final post = PostModel(
        id: '', // Will be generated by Firestore
        memberAuthUid: widget.memberAuthUid,
        memberId: widget.memberId,
        memberName: widget.memberName,
        branch: widget.branch,
        text: text,
        tags: [],
        likeCount: 0,
        commentCount: 0,
        createdAt: Timestamp.now(),
      );

      await _socialService.createPost(post, imageFile: _selectedImage);

      if (mounted) {
        // Pop loading overlay
        Navigator.pop(context);
        // Pop screen
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        // Pop loading overlay
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to create post')),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final text = _textController.text.trim();
    final isSubmitEnabled = !_isSubmitting && (text.isNotEmpty || _selectedImage != null);

    return Scaffold(
      backgroundColor: AppColors.backgroundBlack,
      appBar: AppBar(
        title: Text('Create Post', style: AppTextStyles.heading3),
        backgroundColor: AppColors.backgroundBlack,
        actions: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
            child: ElevatedButton(
              onPressed: isSubmitEnabled ? _submitPost : null,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.neonLime,
                disabledBackgroundColor: AppColors.gray800,
                foregroundColor: Colors.black,
                disabledForegroundColor: AppColors.gray400,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
              ),
              child: const Text('Post', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              children: [
                CircleAvatar(
                  backgroundColor: AppColors.cardSurface,
                  child: Text(
                    widget.memberName.isNotEmpty ? widget.memberName[0].toUpperCase() : '?',
                    style: const TextStyle(color: AppColors.neonLime),
                  ),
                ),
                const SizedBox(width: 12),
                Text(
                  widget.memberName,
                  style: AppTextStyles.bodyLarge.copyWith(fontWeight: FontWeight.bold),
                ),
              ],
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _textController,
              maxLines: null,
              maxLength: 500,
              style: const TextStyle(color: AppColors.white),
              decoration: InputDecoration(
                hintText: "What's on your mind?",
                hintStyle: const TextStyle(color: AppColors.gray400),
                border: InputBorder.none,
                counterStyle: const TextStyle(color: AppColors.gray400),
              ),
              onChanged: (value) => setState(() {}),
            ),
            if (_selectedImage != null) ...[
              const SizedBox(height: 16),
              Stack(
                children: [
                  ClipRRect( // typo: ClipRRect
                    borderRadius: BorderRadius.circular(12),
                    child: Image.file(
                      _selectedImage!,
                      fit: BoxFit.cover,
                      width: double.infinity,
                      height: 200,
                    ),
                  ),
                  Positioned(
                    top: 8,
                    right: 8,
                    child: GestureDetector(
                      onTap: _removeImage,
                      child: Container(
                        padding: const EdgeInsets.all(4),
                        decoration: const BoxDecoration(
                          color: Colors.black54,
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.close, color: Colors.white, size: 20),
                      ),
                    ),
                  ),
                ],
              ),
            ],
            const SizedBox(height: 24),
            Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.image, color: AppColors.neonLime),
                  onPressed: _pickImage,
                  tooltip: 'Add Image',
                ),
                Text(
                  'Add Photo',
                  style: TextStyle(color: AppColors.gray400),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
