// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECFGrE2vvd51ildvQpZKiScE1uz1Kxmo',
    appId: '1:527678863150:web:7ed76c694aefb927eaecbf',
    messagingSenderId: '527678863150',
    projectId: 'spring-health-studio-f4930',
    authDomain: 'spring-health-studio-f4930.firebaseapp.com',
    storageBucket: 'spring-health-studio-f4930.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9y_fTKrfIRYlw4Th_2o93tZUlOsfwu30',
    appId: '1:527678863150:android:b7c18fb4abd67526eaecbf',
    messagingSenderId: '527678863150',
    projectId: 'spring-health-studio-f4930',
    storageBucket: 'spring-health-studio-f4930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4qZeMR0d78FTsVWSpby6fWGIR-amEso',
    appId: '1:527678863150:ios:9493d77549d4286feaecbf',
    messagingSenderId: '527678863150',
    projectId: 'spring-health-studio-f4930',
    storageBucket: 'spring-health-studio-f4930.firebasestorage.app',
    iosBundleId: 'com.example.springHealthStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh4qZeMR0d78FTsVWSpby6fWGIR-amEso',
    appId: '1:527678863150:ios:9493d77549d4286feaecbf',
    messagingSenderId: '527678863150',
    projectId: 'spring-health-studio-f4930',
    storageBucket: 'spring-health-studio-f4930.firebasestorage.app',
    iosBundleId: 'com.example.springHealthStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDECFGrE2vvd51ildvQpZKiScE1uz1Kxmo',
    appId: '1:527678863150:web:8d202dc122e5a1e5eaecbf',
    messagingSenderId: '527678863150',
    projectId: 'spring-health-studio-f4930',
    authDomain: 'spring-health-studio-f4930.firebaseapp.com',
    storageBucket: 'spring-health-studio-f4930.firebasestorage.app',
  );
}
